theme: jekyll-theme-slate

title: "DINO CPU Assignments"
description: "Assignments for UC Davis Computer Architecture 154B. See the <a href=https://jlpteaching.github.io/ECS154B/>Class Website</a> for details"
